import { mkdir, writeFile, chmod, access } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { TUNING } from '../tuning';
if (process.platform !== 'darwin' || !['arm64', 'x64'].includes(process.arch)) throw new Error('This installer is for the verified macOS test host. No system settings were changed.');
const arch = process.arch as 'arm64' | 'x64';
const asset = `cloudflared-darwin-${arch === 'x64' ? 'amd64' : 'arm64'}.tgz`;
const url = `https://github.com/cloudflare/cloudflared/releases/download/${TUNING.tools.cloudflaredVersion}/${asset}`;
await mkdir('.tools', { recursive: true });
const response = await fetch(url);
if (!response.ok) throw new Error(`Official binary download failed: ${response.status}`);
const data = Buffer.from(await response.arrayBuffer());
if (createHash('sha256').update(data).digest('hex') !== TUNING.tools.cloudflaredSha256[arch]) throw new Error('Checksum mismatch. Binary was not installed.');
const archive = `.tools/${asset}`; await writeFile(archive, data);
const entries = execFileSync('tar', ['-tzf', archive], { encoding: 'utf8' }).trim().split('\n');
if (entries.some(entry => entry !== 'cloudflared')) throw new Error('Unexpected archive entries.');
execFileSync('tar', ['-xzf', archive, '-C', '.tools']);
await chmod('.tools/cloudflared', 0o755); await access('.tools/cloudflared');
console.log(execFileSync('.tools/cloudflared', ['--version'], { encoding: 'utf8' }).trim());
console.log('Official checksum verified. Installed project-locally. No account, card, tunnel, or hosted resource created.');
